service: kinesis-datastream-consumer-lambda

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-northeast-1
  profile: ${self:custom.profiles.${sls:stage}}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - kinesis:*
          Resource: "*"

custom:
  profiles:
    dev: ${env:PROFILE}                 # set aws profile at dev stage.
    prod: ${env:PROFILE}                # set aws profile at prod stage.
    local: ${env:PROFILE}               # set aws profile at local stage.
  kinesis-name: "my-kinesis"
  offlineKinesisStreams:
    port: 4567
    region: local
    streams:
      - streamName: ${self:custom.kinesis-name}
        shards: 1

functions:
  compute:
    handler: handler.kinesisConsumer
    events:
      - stream:
          enabled: true
          type: kinesis
          arn: arn:aws:kinesis:${self:provider.region}:${aws:accountId}:stream/${self:custom.kinesis-name}
          batchSize: 10
          startingPosition: LATEST

plugins:
  - serverless-offline-kinesis-streams
  - serverless-offline
