env:
  commonjs: true
  es2021: true
  jest: true
extends:
  - eslint:recommended
  - plugin:node/recommended
  - prettier
parserOptions:
  ecmaVersion: latest
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  camelcase:
    - error
    - properties: always
  no-loss-of-precision:
    - 0
