service: sqs-consumer-lambda

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-northeast-1
  profile: ${self:custom.profiles.${sls:stage}}
  iam:
    role:
      managedPolicies:
        - "arn:aws:iam::aws:policy/AmazonSQSFullAccess"

custom:
  profiles:
    dev: ${env:PROFILE}                 # set aws profile at dev stage.
    prod: ${env:PROFILE}                # set aws profile at prod stage.
    local: ${env:PROFILE}               # set aws profile at local stage.
  queue-name: "my-queue"
  jest:
    testTimeout: 30000

  serverless-offline-sqs:
    autoCreate: yes
    apiVersion: '2012-11-05'
    endpoint: http://127.0.0.1:9324
    accessKeyId: root
    secretAccessKey: root

functions:
  compute:
    handler: handler.compute
    events:
      - sqs:
          arn: arn:aws:sqs:${self:provider.region}:${aws:accountId}:${self:custom.queue-name}
          batchSize: 1
          maximumBatchingWindow: 0
          functionResponseType: ReportBatchItemFailures
          enabled: true

resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:custom.queue-name}

plugins:
  - serverless-offline-sqs      # order is important
  - serverless-offline
  - serverless-jest-plugin
